#!/bin/sh
# Install a `blitzkrieg` command shim into a PATH directory, so the launcher
# works as plain `blitzkrieg run` / `blitzkrieg stop` from ANY directory.
#
# WHY A SHIM AND NOT A COPY (or `cargo install`)
#   This is a dev checkout: the binary is rebuilt constantly, the core binary
#   and the strategy cdylibs are resolved relative to the repo root, and the
#   repo path contains a space. The shim therefore does exactly three things —
#   cd to the repo root it was generated from, exec the freshly built binary
#   there, and pass every argument through — so it can never go stale and the
#   core/strategy/data resolution keeps its existing, tested semantics.
#
# WHAT IT WRITES
#   One small script at $BLITZKRIEG_SHIM_DIR (default ~/.local/bin if it is on
#   PATH, else /opt/homebrew/bin) named `blitzkrieg`. It overwrites only a file
#   that is itself a BlitzkriegBot shim; anything else is refused.
#
# Usage:
#   bash scripts/install-blitzkrieg-shim.sh
#   BLITZKRIEG_SHIM_DIR=/usr/local/bin bash scripts/install-blitzkrieg-shim.sh

set -eu

repo_root=$(cd "$(dirname "$0")/.." && pwd)
binary="$repo_root/target/release/blitzkrieg"

if [ ! -x "$binary" ]; then
    echo "error: $binary not built yet. Run first:"
    echo "  cargo build --release --workspace --locked"
    exit 1
fi

# Prefer a directory that is already on PATH: ~/.local/bin first (user-owned,
# no sudo), then /opt/homebrew/bin, then /usr/local/bin.
default_dir=""
for d in "$HOME/.local/bin" /opt/homebrew/bin /usr/local/bin; do
    case ":$PATH:" in
        *":$d:"*) default_dir="$d"; break ;;
    esac
done
if [ -z "$default_dir" ]; then
    default_dir="$HOME/.local/bin"
    echo "note: none of ~/.local/bin, /opt/homebrew/bin, /usr/local/bin is on PATH;"
    echo "      installing to $default_dir — add it to PATH to use the command."
fi
shim_dir="${BLITZKRIEG_SHIM_DIR:-$default_dir}"
shim="$shim_dir/blitzkrieg"

mkdir -p "$shim_dir"

if [ -e "$shim" ] && ! grep -q "BlitzkriegBot shim" "$shim" 2>/dev/null; then
    echo "error: $shim already exists and is not a BlitzkriegBot shim; refusing to overwrite."
    echo "       Move it aside, or point BLITZKRIEG_SHIM_DIR somewhere else."
    exit 1
fi

# The path is baked in at install time: this checkout is the deployment.
{
    echo '#!/bin/sh'
    echo '# BlitzkriegBot shim — generated by scripts/install-blitzkrieg-shim.sh.'
    echo '# Regenerate after moving the checkout: the repo path is baked in.'
    echo "cd \"$repo_root\" || exit 1"
    echo 'exec ./target/release/blitzkrieg "$@"'
} > "$shim"
chmod +x "$shim"

echo "installed: $shim  ->  $binary"
case ":$PATH:" in
    *":$shim_dir:"*) ;;
    *) echo "warning: $shim_dir is not on PATH; add 'export PATH=\"$shim_dir:\$PATH\"' to your shell profile." ;;
esac
echo "try: blitzkrieg --help"
